export const ROUTE_MAP = {
    // Vietnamese route keywords
    "trang chủ": "/",
    "trang chu": "/",
    "home": "/",
    "sản phẩm": "/products",
    "san pham": "/products",
    "products": "/products",
    "giỏ hàng": "/cart",
    "gio hang": "/cart",
    "cart": "/cart",
    "tài khoản": "/account",
    "tai khoan": "/account",
    "account": "/account",
    "đăng nhập": "/login",
    "dang nhap": "/login",
    "login": "/login",
    "đăng ký": "/register",
    "dang ky": "/register",
    "register": "/register",
    "blog": "/blog",
    "tin tức": "/blog",
    "tin tuc": "/blog",
    "liên hệ": "/lien-he",
    "lien he": "/lien-he",
    "contact": "/lien-he",
    "giới thiệu": "/gioi-thieu",
    "gioi thieu": "/gioi-thieu",
    "about": "/gioi-thieu",
    "địa chỉ": "/account/addresses",
    "dia chi": "/account/addresses",
    "addresses": "/account/addresses",
    "đơn hàng": "/account/orders",
    "don hang": "/account/orders",
    "orders": "/account/orders",
    "danh sách ưa thích": "/account/wishlist",
    "danh sach ua thich": "/account/wishlist",
    "wishlist": "/account/wishlist",
    "yêu thích": "/account/wishlist",
    "yeu thich": "/account/wishlist",
    // Product categories
    "rượu vang đỏ": "/products?category=Rượu Vang Đỏ",
    "ruou vang do": "/products?category=Rượu Vang Đỏ",
    "red wine": "/products?category=Rượu Vang Đỏ",
    "rượu vang trắng": "/products?category=Rượu Vang Trắng",
    "ruou vang trang": "/products?category=Rượu Vang Trắng",
    "white wine": "/products?category=Rượu Vang Trắng",
    "champagne": "/products?category=Champagne",
    "rượu vang rosé": "/products?category=Rượu Vang Rosé",
    "ruou vang rose": "/products?category=Rượu Vang Rosé",
    "rosé": "/products?category=Rượu Vang Rosé",
    "rose": "/products?category=Rượu Vang Rosé",
    "rượu vang ngọt": "/products?category=Rượu Vang Ngọt",
    "ruou vang ngot": "/products?category=Rượu Vang Ngọt",
    "sweet wine": "/products?category=Rượu Vang Ngọt",
};
